#!/bin/bash
set -e

step() {
  echo -e "\e[30mnginx\e[0m >> \e[33m${1}\e[0m"
}

step "Configurando apache...";
dockerize \
    -template conf/extra/httpd-vhosts.conf:conf/extra/httpd-vhosts.conf \
	-template conf/extra/httpd-vhosts-ssl.conf:conf/extra/httpd-vhosts-ssl.conf

if [ "${SSL}" == "true" ]; then
	step "Configurando SSL...";

	sed -i \
		-e 's/^#\(Include .*httpd-ssl.conf\)/\1/' \
		-e 's/^#\(LoadModule .*mod_ssl.so\)/\1/' \
		-e 's/^#\(LoadModule .*mod_socache_shmcb.so\)/\1/' \
		conf/httpd.conf

	echo "Include conf/extra/httpd-vhosts-ssl.conf" >> conf/httpd.conf;
fi

if [ -n "${HOST_PHP}" ]; then
	dockerize \
		-wait tcp://${HOST_PHP}:${PORTA_PHP} \
		-timeout ${TIMEOUT_PHP} \
	httpd-foreground
else
	httpd-foreground
fi